ARG ALPINE_DIGEST=sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
ARG RUST_DIGEST=sha256:a96ea6d18d4062e38f16cfbadd8b4541d622f2527dd0a5eca1fb36d301da4e88

FROM alpine@${ALPINE_DIGEST} AS alpine-base
FROM rust@${RUST_DIGEST} AS rust-base

FROM alpine-base AS verifier

ARG COMMIT_HASH

RUN apk add --no-cache git ca-certificates

WORKDIR /verify

RUN git init . && \
    git remote add origin https://github.com/kengzzzz/helium-service.git && \
    git fetch --depth 1 origin "${COMMIT_HASH}" && \
    git checkout FETCH_HEAD

FROM rust-base AS builder

RUN apk update && apk upgrade && apk add --no-cache \
    build-base ca-certificates

ENV RUSTFLAGS="-C target-feature=+crt-static -C target-cpu=native"

WORKDIR /src

COPY --from=verifier /verify/ ./

RUN export TARGET=$(rustc -vV | sed -n 's/host: //p') && \
    cargo build --release --locked --target "$TARGET" --bin helium-service && \
    mkdir -p /rootfs/etc/ssl/certs /rootfs/usr/local/bin /rootfs/app /rootfs/tmp/helium-dictionaries && \
    cp "target/$TARGET/release/helium-service" /rootfs/usr/local/bin/helium-service && \
    cp /etc/ssl/certs/ca-certificates.crt /rootfs/etc/ssl/certs/ && \
    echo "helium:x:1000:1000:helium:/app:/sbin/nologin" > /rootfs/etc/passwd && \
    echo "helium:x:1000:" > /rootfs/etc/group && \
    chmod 1777 /rootfs/tmp && \
    chown 1000:1000 /rootfs/app && \
    chown 1000:1000 /rootfs/tmp/helium-dictionaries

FROM scratch AS exporter

COPY --from=builder /rootfs/ /

FROM scratch

COPY --from=exporter / /

USER 1000:1000

WORKDIR /app

HEALTHCHECK --start-period=3s --start-interval=5s --interval=5m --timeout=10s CMD ["helium-service", "healthcheck"]

ENTRYPOINT ["helium-service"]
