FROM rust:slim-trixie@sha256:d6782f2b326a10eaf593eb90cafc34a03a287b4a25fe4d0c693c90304b06f6d7 AS builder

ARG VERSION COMMIT_HASH
ENV RUSTFLAGS="-C target-feature=+crt-static -C target-cpu=native" CXXFLAGS="-w -fpermissive -include cstdint" \
    LIBROCKSDB_SYS_STATIC=1 CARGO_PROFILE_RELEASE_OPT_LEVEL="3" CARGO_PROFILE_RELEASE_CODEGEN_UNITS="1" CARGO_PROFILE_RELEASE_LTO="fat" CARGO_PROFILE_RELEASE_PANIC="abort" CARGO_PROFILE_RELEASE_STRIP="true"

RUN apt-get update && apt-get install -y --no-install-recommends build-essential cmake git pkg-config libsnappy-dev libzstd-dev liblz4-dev zlib1g-dev libbz2-dev libssl-dev clang llvm-dev libclang-dev ca-certificates tzdata musl-tools

WORKDIR /build

RUN git clone --depth 1 --branch ${VERSION} https://github.com/romanz/electrs . && \
    [ -n "$COMMIT_HASH" ] && [ "$(git rev-parse HEAD)" = "$COMMIT_HASH" ] || { echo "Hash mismatch"; exit 1; }

RUN export TARGET=$(rustc -vV | sed -n 's/host: //p') && cargo build --no-default-features --locked --release --target "$TARGET" && cp "target/$TARGET/release/electrs" target/release/electrs

RUN cat <<EOF > healthcheck.c
#include <arpa/inet.h>
#include <sys/socket.h>
#include <unistd.h>
#include <stdlib.h>
int main(int argc, char* argv[]) {
    if (argc != 3) return 1;
    int sock = socket(AF_INET, SOCK_STREAM, 0);
    if (sock < 0) return 1;
    struct sockaddr_in addr = {0};
    addr.sin_family = AF_INET;
    addr.sin_port = htons(atoi(argv[2]));
    inet_pton(AF_INET, argv[1], &addr.sin_addr);
    int r = connect(sock, (struct sockaddr *)&addr, sizeof(addr));
    close(sock);
    return (r == 0) ? 0 : 1;
}
EOF

RUN musl-gcc -static -Os -s -fno-stack-protector -fno-asynchronous-unwind-tables -fno-ident -o healthcheck healthcheck.c

RUN mkdir -p /rootfs/etc/ssl/certs /rootfs/usr/bin /rootfs-writable/data /rootfs-writable/tmp && \
    echo "electrs:x:1000:1000:electrs:/data:/sbin/nologin" > /rootfs/etc/passwd && echo "electrs:x:1000:" > /rootfs/etc/group && \
    cp /etc/ssl/certs/ca-certificates.crt /rootfs/etc/ssl/certs/ && cp target/release/electrs /rootfs/usr/bin/ && cp healthcheck /rootfs/usr/bin/ && \
    chmod 1777 /rootfs-writable/tmp

FROM scratch

COPY --from=builder /rootfs/ /

COPY --from=builder --chown=1000:1000 /rootfs-writable/ /

USER 1000:1000

WORKDIR /data

HEALTHCHECK --interval=60s --timeout=5s --start-period=15s --retries=3 CMD ["/usr/bin/healthcheck", "127.0.0.1", "50001"]

ENTRYPOINT ["/usr/bin/electrs"]
CMD ["--conf=/data/config.toml"]