ARG ALPINE_DIGEST=sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
ARG GOLANG_DIGEST=sha256:3ad57304ad93bbec8548a0437ad9e06a455660655d9af011d58b993f6f615648

FROM alpine@${ALPINE_DIGEST} AS alpine-base
FROM golang@${GOLANG_DIGEST} AS golang-base

FROM alpine-base AS verifier

ARG COMMIT_HASH

RUN apk add --no-cache git ca-certificates

WORKDIR /verify

RUN git init . && \
    git remote add origin https://github.com/henrygd/beszel.git && \
    git fetch --depth 1 origin "${COMMIT_HASH}" && \
    git checkout FETCH_HEAD

FROM golang-base AS builder

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /build

COPY --from=verifier /verify/ ./

WORKDIR /build/internal/cmd/agent

RUN CGO_ENABLED=0 go build -trimpath -ldflags="-w -s" -o /build/beszel-agent ./agent.go

RUN echo "beszel:x:1000:1000:beszel:/nonexistent:/sbin/nologin" > /etc/passwd.custom && \
    echo "beszel:x:1000:" > /etc/group.custom

FROM scratch AS exporter

COPY --from=builder /etc/passwd.custom /etc/passwd
COPY --from=builder /etc/group.custom /etc/group
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /usr/share/zoneinfo/Asia/Bangkok /usr/share/zoneinfo/Asia/Bangkok
COPY --from=builder /build/beszel-agent /usr/local/bin/agent

FROM scratch

COPY --from=exporter / /

USER 1000:1000

ENV TZ=Asia/Bangkok

HEALTHCHECK --interval=120s --timeout=10s --start-period=10s --retries=3 CMD ["agent", "health"]

ENTRYPOINT ["agent"]