ARG ALPINE_DIGEST=sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
ARG GOLANG_DIGEST=sha256:8a5910f31396cd4d89662f56c68b3ae31d374308270a1c3bd96672ee5ed43414

FROM alpine@${ALPINE_DIGEST} AS alpine-base
FROM golang@${GOLANG_DIGEST} AS golang-base

FROM alpine-base AS verifier

ARG COMMIT_HASH

RUN apk add --no-cache git ca-certificates

WORKDIR /verify

RUN git init . && \
    git remote add origin https://github.com/henrygd/beszel.git && \
    git fetch --depth 1 origin "${COMMIT_HASH}" && \
    git checkout FETCH_HEAD

FROM golang-base AS builder

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /build

COPY --from=verifier /verify/ ./

WORKDIR /build/internal/cmd/agent

RUN CGO_ENABLED=0 go build -trimpath -ldflags="-w -s" -o /build/beszel-agent ./agent.go

RUN echo "beszel:x:1000:1000:beszel:/nonexistent:/sbin/nologin" > /etc/passwd.custom && \
    echo "beszel:x:1000:" > /etc/group.custom

FROM scratch AS exporter

COPY --from=builder /etc/passwd.custom /etc/passwd
COPY --from=builder /etc/group.custom /etc/group
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /usr/share/zoneinfo/Asia/Bangkok /usr/share/zoneinfo/Asia/Bangkok
COPY --from=builder /build/beszel-agent /usr/local/bin/agent

FROM scratch

COPY --from=exporter / /

USER 1000:1000

ENV TZ=Asia/Bangkok

HEALTHCHECK --interval=120s --timeout=10s --start-period=10s --retries=3 CMD ["agent", "health"]

ENTRYPOINT ["agent"]
